<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StaffSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    // 'TỔ HOÀN THÀNH' : 1
    // 'TỔ SẢN XUẤT' : 2
    // 'TỔ ĐIỀU HÀNH' : 3
    // 'TỔ SẢN XUẤT' : 4
    public function run()
    {
        DB::table('users')->insert([
            [
                'full_name'     => 'Dương Quý Việt',
                'board_id'      => 1,
                'title_level'   => 'CƠ ĐIỆN',
                'stk'           =>  '105006059179',
                'bank'          => 'Viettinbank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Nguyễn Tiến',
                'board_id'      => 1,
                'title_level'   => 'ĐÓNG GÓI',
                'stk'           =>  '105874043112',
                'bank'          => 'Viettinbank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Trần Xuân Vũ',
                'board_id'      => 1,
                'title_level'   => 'ĐÓNG GÓI',
                'stk'           =>  '0399414409',
                'bank'          => 'MBBank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Lê Thi Thương',
                'board_id'      => 1,
                'title_level'   => '',
                'stk'           =>  '',
                'bank'          => '',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Nguyễn Thị Thu 2',
                'board_id'      => 2,
                'title_level'   => 'GẤP XẾP',
                'stk'           =>  '0796791006',
                'bank'          => 'Eximbank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Nguyễn Thị Nga',
                'board_id'      => 2,
                'title_level'   => 'GẤP XẾP',
                'stk'           =>  '0796791006',
                'bank'          => 'Eximbank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Nguyễn Thị Thu 3',
                'board_id'      => 2,
                'title_level'   => 'GẤP XẾP',
                'stk'           =>  '0796791006',
                'bank'          => 'Eximbank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Đỗ Thị Phương Thuỷ',
                'board_id'      => 2,
                'title_level'   => 'GẤP XẾP',
                'stk'           =>  '105871686897',
                'bank'          => 'Viettinbank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Phạm Thị Liên',
                'board_id'      => 2,
                'title_level'   => 'GẤP XẾP',
                'stk'           =>  '0651000847822',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Đặng Thị Vân',
                'board_id'      => 2,
                'title_level'   => 'GẤP XẾP',
                'stk'           =>  '',
                'bank'          => '',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Đặng Thị Vân',
                'board_id'      => 2,
                'title_level'   => 'GẤP XẾP',
                'stk'           =>  '',
                'bank'          => '',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Nguyễn Thị Mỹ Linh',
                'board_id'      => 1,
                'title_level'   => 'KIỂM HÀNG',
                'stk'           =>  '106876629570',
                'bank'          => 'Vietinbank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Nguyễn Thị Hiền',
                'board_id'      => 1,
                'title_level'   => 'KIỂM HÀNG',
                'stk'           =>  '106876629570',
                'bank'          => 'Vietinbank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Lê Thị Hết',
                'board_id'      => 3,
                'title_level'   => 'TẠP VỤ',
                'stk'           =>  '15986787',
                'bank'          => 'ACB',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Lê Thị Phương Thảo',
                'board_id'      => 2,
                'title_level'   => 'TỔ TRƯỞNG',
                'stk'           =>  '0796791006',
                'bank'          => 'Eximbank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Võ Thị Dung',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '19035790234013',
                'bank'          => 'Techcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Đoàn Thị Thanh Ngân',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000848636',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Dương Thị Ngọc Lan',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '19038530435014',
                'bank'          => 'Techcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Trần Thị Bình',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000848022',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Dương Thị Vi',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '4202205211283',
                'bank'          => 'Agribank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],[
                'full_name'     => 'Nguyễn Thị Tuyết Xưng',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000880075',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Lê Thị Liên',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000848696',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Tống Thị Thúy',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000847885',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Nguyễn Thị Huyền Trang',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000848637',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Dương Thị Yến',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000848095',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Thái Thị Hồng Vân',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000847804',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Đoàn Thị Thơm',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000848147',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Hà Thị Bích',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '1023710734',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Lê Thị Hồng Lài',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '19038572219011',
                'bank'          => 'Nguyễn Thị Thuỳ',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Nguyễn Thị Thuỳ',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000848432',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],[
                'full_name'     => 'Lê thị Tâm Như',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0834076049',
                'bank'          => 'MBBank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],[
                'full_name'     => 'Hà Thị Bích',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '1023710734',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Võ Thị Hân',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000884571',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Hà Thị Phương Dung',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000848936',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Đặng Ngọc Thuý Hiền',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0972701524',
                'bank'          => 'VPBank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Hà Thị Bích',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '1023710734',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Nguyễn Thị Cúc',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000848915',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Nguyễn Thị Mỹ Dung',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000880075',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Nguyễn Thị Nhật Trinh',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000854364',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Trần Thị Minh Lộc',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '42022051722890',
                'bank'          => 'Agribank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Trần Thị Song',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0934310990',
                'bank'          => 'MBBank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Phan Thị Trinh',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0365860532',
                'bank'          => 'MBBank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Trương Thị Xuân',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0211000488692',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Nguyễn Thị Trang',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0905719441',
                'bank'          => 'MBBank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Trương Thị Huệ',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '0651000848960',
                'bank'          => 'Vietcombank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Phan Hồ Anh Thư',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '4219205084150',
                'bank'          => 'Agribank',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Huỳnh Thị Kim Sa',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '',
                'bank'          => '',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Trần Thị Cảnh',
                'board_id'      => 2,
                'title_level'   => 'CÔNG NHÂN MAY',
                'stk'           =>  '',
                'bank'          => '',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Trương Thị Hồng',
                'board_id'      => 1,
                'title_level'   => 'GẤP XẾP',
                'stk'           =>  '',
                'bank'          => '',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Nguyễn Chí Quang',
                'board_id'      => 1,
                'title_level'   => 'ĐÓNG GÓI',
                'stk'           =>  '',
                'bank'          => '',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Nguyễn Văn Hùng',
                'board_id'      => 1,
                'title_level'   => 'ĐÓNG GÓI',
                'stk'           =>  '',
                'bank'          => '',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Lê Văn Linh',
                'board_id'      => 1,
                'title_level'   => 'ĐÓNG GÓI',
                'stk'           =>  '',
                'bank'          => '',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'full_name'     => 'Lê Văn Hà',
                'board_id'      => 1,
                'title_level'   => 'ĐÓNG GÓI',
                'stk'           =>  '',
                'bank'          => '',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
        ]);
    }
}
